---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.SGMR_SERVICE_NAME}}"
spec:
  selector:
    matchLabels:
      name: "{{.SGMR_SERVICE_NAME}}"
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: "{{.SGMR_SERVICE_NAME}}"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {{.SGMR_SERVICE_NAME}}-proxy
        image: "{{.NGINX_IMAGE}}:{{.NGINX_TAG}}"
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
         limits:
          memory: "100Mi"
          cpu: "100m"
         requests:
          memory: "50Mi"
          cpu: "100m"
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: "{{.SGMR_SERVICE_PORT}}"
          - name: SERVER_CERT
            value: "/certs/tls.crt"
          - name: SERVER_KEY
            value: "/certs/tls.key"
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: STATSD_METRICS
            value: "FALSE"
        ports:
          - name: https
            containerPort: 10443
        volumeMounts:
          - name: certs
            mountPath: /certs
      - name: "{{.SGMR_SERVICE_NAME}}"
        image: "{{.SGMR_SERVICE_IMAGE}}:{{.SGMR_SERVICE_TAG}}"
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2304Mi"
            cpu: "1000m"
          limits:
            memory: "2304Mi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{.SGMR_SERVICE_PORT}}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{.SGMR_SERVICE_PORT}}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
      volumes:
      - name: certs
        secret:
          secretName: "{{.SGMR_SERVICE_NAME}}-pod-tls"
